# Generated by Django 4.0.2 on 2022-02-15 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_homepage_banner_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='excerpt',
        ),
    ]
