# Generated by Django 4.0.2 on 2022-02-16 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_aboutpage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AboutPage',
        ),
    ]
