# Generated by Django 4.0.2 on 2022-02-17 17:29

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallerypage',
            name='excerpt',
        ),
        migrations.RemoveField(
            model_name='gallerypage',
            name='image',
        ),
        migrations.AddField(
            model_name='gallerypage',
            name='gallery_photo',
            field=wagtail.core.fields.StreamField([('image', wagtail.images.blocks.ImageChooserBlock()), ('description', wagtail.core.blocks.CharBlock())], blank=True, null=True),
        ),
    ]
