# Generated by Django 4.0.2 on 2022-02-16 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutpage',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
