# Generated by Django 4.0.2 on 2022-02-16 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_alter_aboutpage_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutpage',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
