# Generated by Django 4.0.2 on 2022-02-16 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blogpage_main_image_excerpt'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpage',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
